// FRAMEWORK-OWNED REFERENCE (ADR-0029). Style Dictionary build: DTCG tokens.json
// (+ tokens.dark.json) -> src/styles/tokens.generated.css (the :root / .dark
// CSS-variable layer). This is the ONE place token VALUES turn into the CSS vars
// that tailwind.config.ts binds via hsl(var(--token)) — so there is no hand-drift
// between the design tokens and the theme. Run with `npm run tokens:build`
// (also invoked by `predev` / `prebuild`). The generated file is committed but
// MUST NOT be hand-edited; regenerate from the tokens instead.
//
// CALIBRATION POINT (foundation milestone): pin the style-dictionary version in
// package.json, run `npm install` then `npm run tokens:build`, and COMMIT the real
// generated output. If your installed Style Dictionary major (v4 here) changes the
// programmatic API (registerTransform/registerFormat signatures, `transform` vs
// `transformer`, the format `format` fn args), adjust below to match — the contract
// to preserve is: bare HSL channels for `$type: color`, `<n><unit>` for
// `$type: dimension`, var name = the leaf token name (so `--primary`, not
// `--color-primary`), and a `:root` block from tokens.json + a `.dark` block from
// tokens.dark.json, wrapped in `@layer base`.

import StyleDictionary from "style-dictionary";
import { readFileSync, writeFileSync, rmSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(here, "src/styles/tokens.generated.css");

// color: "hsl(222.2 47.4% 11.2%)" -> "222.2 47.4% 11.2%" (bare HSL channels, so the
// existing hsl(var(--token)) binding and hsl(var(--token) / <alpha>) both work).
StyleDictionary.registerTransform({
  name: "cr/hslChannels",
  type: "value",
  transitive: true,
  filter: (t) => t.$type === "color",
  transform: (t) => String(t.$value).replace(/^hsl\(\s*/i, "").replace(/\s*\)\s*$/, ""),
});

// dimension: { value: 0.5, unit: "rem" } -> "0.5rem"
StyleDictionary.registerTransform({
  name: "cr/dimToCss",
  type: "value",
  transitive: true,
  filter: (t) => t.$type === "dimension",
  transform: (t) =>
    t.$value && typeof t.$value === "object" ? `${t.$value.value}${t.$value.unit}` : String(t.$value),
});

// var name = leaf token name only (drop the `color.` group prefix): `--primary`.
StyleDictionary.registerTransform({
  name: "cr/varName",
  type: "name",
  transform: (t) => t.path[t.path.length - 1],
});

// One CSS selector block of `--name: value;` declarations.
StyleDictionary.registerFormat({
  name: "cr/cssSelectorBlock",
  format: ({ dictionary, options }) => {
    // SD v4 keeps the transformed value on `$value` in DTCG mode (`value` is the
    // legacy field) — read whichever is populated. CALIBRATION POINT if upgrading.
    const decls = dictionary.allTokens
      .map((t) => `    --${t.name}: ${t.$value ?? t.value};`)
      .join("\n");
    return `  ${options.selector} {\n${decls}\n  }\n`;
  },
});

async function buildBlock(source, selector, tmpName) {
  const sd = new StyleDictionary({
    source,
    platforms: {
      css: {
        transforms: ["cr/hslChannels", "cr/dimToCss", "cr/varName"],
        buildPath: resolve(here, "src/styles") + "/",
        files: [{ destination: tmpName, format: "cr/cssSelectorBlock", options: { selector } }],
      },
    },
    log: { verbosity: "silent" },
  });
  await sd.buildAllPlatforms();
  const path = resolve(here, "src/styles", tmpName);
  const body = readFileSync(path, "utf8");
  rmSync(path, { force: true });
  return body;
}

const root = await buildBlock(["tokens.json"], ":root", "__root.css");
const dark = await buildBlock(["tokens.json", "tokens.dark.json"], ".dark", "__dark.css");

const banner =
  "/* GENERATED by Style Dictionary from tokens.json + tokens.dark.json (ADR-0029).\n" +
  "   DO NOT EDIT BY HAND — run `npm run tokens:build`. The tier-1 structural token\n" +
  "   check asserts this file stays consistent with the DTCG tokens. */\n";

writeFileSync(OUT, `${banner}@layer base {\n${root}\n${dark}}\n`, "utf8");
